FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git\
    unzip\
    curl\
    libzip-dev\
    libpq-dev\
    libonig-dev\
    libxml2-dev\
    && docker-php-ext-install pdo pdo_mysql zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY blog-app-backend/. .

RUN composer install 

EXPOSE 8000
CMD ["php","artisan","serve","--host=0.0.0.0","--port=8000"]